Repository CosmoStat/Shear-and-PSF-Reading-Group, pull requests merged in 2021-07, with the labels that each got.

#57 Add .DS_Store to gitignore list
  .DS_Store
  .gitignore
Labels: clean up

#59 fixing documentation
  shearbook/contrib/guidelines.md
Labels: clean up, documentation

#58 Style multi line
  shearbook/contrib/style.md
Labels: documentation

#60 Reorganise PSF intro section
  shearbook/_toc.yml
  shearbook/psf/1-intro/contributions.md
  shearbook/psf/1-intro/definitions.md
  shearbook/psf/1-intro/examples.ipynb
  shearbook/psf/psf-intro.md
Labels: clean up

#56 ShearBook environment and config
  .github/workflows/deploy_dev.yml
  .github/workflows/deploy_pages.yml
  .github/workflows/test_build.yml
  Dockerfile
  README.md
  environment.yml
  requirements.txt
  shearbook/_config.yml
Labels: clean up

#52 Adding page on rho statistics
  notebooks/rho-statistics.ipynb
  shearbook/_bibliography/z_psf_validation.bib
  shearbook/_config.yml
  shearbook/psf/rho-statistics.ipynb
Labels: enhancement
